project:
  type: website

website:
  title: "Introduction"
  page-navigation: true

  sidebar: 
    title: "Intermediate Python"
    logo: "assets/UoB_RGB_24.png"
    logo-alt: "Jean Golding Institute Logo"
    style: "docked"
    border: true
    contents: 
      - "index.qmd"
      - "pages/001-workspace-setup.qmd"
      - section: "pages/010-advanced-data-types.qmd"
        contents:
          - "pages/011-dictionaries.qmd"
          - "pages/012-string-formatting.qmd"
          - "pages/013-list-comprehensions.qmd"
      - section: "pages/020-functions.qmd"
        contents:
          - "pages/021-importing-functions.qmd"
          - "pages/022-writing-functions.qmd"
      - "pages/030-modules.qmd"
      - "pages/040-errors-exceptions.qmd"
      - "pages/980-summary.qmd"
      - "pages/990-contributors.qmd"


  page-footer:
    left: "Course delivered by the [Jean Golding Institute](https://www.bristol.ac.uk/golding/)<br>© [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/)"  
  repo-url: https://github.com/uob-training/beginning-python
  repo-actions: [edit, issue]

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
    shift-heading-level-by: 1
    highlight-style: github

    # code-line-numbers: true

execute:
  freeze: auto
  error: true

